# Generated by Django 3.1 on 2020-08-16 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("agile", "0002_alter_agile_principle_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="agile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
